// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwVth4rE9uUQdeeUWnUUYCVQx2AiyJ-Ec',
    appId: '1:814430763125:web:e4f258d0541cac7422a03c',
    messagingSenderId: '814430763125',
    projectId: 'smart-health-be83c',
    authDomain: 'smart-health-be83c.firebaseapp.com',
    storageBucket: 'smart-health-be83c.firebasestorage.app',
    measurementId: 'G-RMRHL5YC6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3PdlGhjttNuB_ri8VMM4fut4oT1HyOWA',
    appId: '1:814430763125:android:75d9ab53f1a96a8922a03c',
    messagingSenderId: '814430763125',
    projectId: 'smart-health-be83c',
    storageBucket: 'smart-health-be83c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR4nDMROI_qD0R38vI8f9XOSDB0ugRpfI',
    appId: '1:814430763125:ios:7f3d7620b339e11e22a03c',
    messagingSenderId: '814430763125',
    projectId: 'smart-health-be83c',
    storageBucket: 'smart-health-be83c.firebasestorage.app',
    iosBundleId: 'com.example.smartHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR4nDMROI_qD0R38vI8f9XOSDB0ugRpfI',
    appId: '1:814430763125:ios:7f3d7620b339e11e22a03c',
    messagingSenderId: '814430763125',
    projectId: 'smart-health-be83c',
    storageBucket: 'smart-health-be83c.firebasestorage.app',
    iosBundleId: 'com.example.smartHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwVth4rE9uUQdeeUWnUUYCVQx2AiyJ-Ec',
    appId: '1:814430763125:web:ac1634ccdfc8e5f622a03c',
    messagingSenderId: '814430763125',
    projectId: 'smart-health-be83c',
    authDomain: 'smart-health-be83c.firebaseapp.com',
    storageBucket: 'smart-health-be83c.firebasestorage.app',
    measurementId: 'G-3XKZZSVMBP',
  );
}
